### ISSUE TITLE
Large full backup

### ISSUE THREAD

**Issue by alexbowers** [canton7/s3-tar-backup#3]
Is it possible for a "full" backup to be chunked?

We have a 400gb storage drive to backup, attached to a 20gb virtual server.

We _could_ assign another 400gb drive, but it would be better if we could have it chunked into 10gb blocks.

Is this a feature that could be considered?

**Comment by alexbowers** [comment]
Note: our `backup_dir` is attached to the 20gb virtual server.

**Comment by canton7** [comment]
I'm afraid I'm not actively developing this project (I'll update the README). Contributions see accepted, but i'm afraid I don't have time to work on it these days.
