### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by alexbowers** [canton7/s3-tar-backup#4]
HI @canton7 I know you're no longer supporting this, but a new release to get some features out would be much appreciated.

In particular, i'm looking for the No Compression feature.

Thanks.

**Comment by alexbowers** [comment]
@canton7 Any chance you can add me as a maintainer so I can produce releases on this?

Thanks.

**Comment by canton7** [comment]
Uploaded!

**Comment by alexbowers** [comment]
Thank you :)

**Comment by alexbowers** [comment]
Can this be marked as "Latest Release" on GitHub too?

Thanks.
